// Generated by https://quicktype.io

export interface RatingRequest {
    songId: number;
    action: string;
}

export interface RatingResponse {
    likes: number;
    dislikes: number;
}

export enum RatingAction {
    LIKE = "LIKE",
    DISLIKE = "DISLIKE",
    REMOVE_LIKE = "REMOVE_LIKE",
    REMOVE_DISLIKE = "REMOVE_DISLIKE"
}